project:
  type: website
  output-dir: docs

website:
  title: "Zhenglei Gao"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: "Blog"

  sidebar:
    - title: "About Me"
      style: "docked"
      contents:
        - about.qmd


    - title: "Memo"
      contents:
        - blog.qmd

    - title: "Fundamentals"
      contents:
        - fundamentals.qmd

    - title: "Reference"
      contents:
        - reference.qmd


format:
  html:
    theme:
      light: minty
      dark: solar
    css: styles.css
    toc: true

editor: source

