project:
  type: website
  output-dir: docs

website:
  title: "Zhenglei Gao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: "Blog"
  sidebar:
    - title: "Blog"
      style: "docked"
      background: light
      contents: posts
        - tutorials.qmd
        - tutorial-1.qmd
        - tutorial-2.qmd

format:
  html:
    theme:
      light: minty
      dark: solar
    css: styles.css
    toc: true

editor: visual

