project:
  type: website
  output-dir: docs

website:
  title: "Zhenglei Gao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: "Blog"
  sidebar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Zhenglei-BCS/Zhenglei-BCS.github.io
          - text: Report a Bug
            href:  https://github.com/Zhenglei-BCS/Zhenglei-BCS.github.io/issues


format:
  html:
    theme:
      light: minty
      dark: solar
    css: styles.css
    toc: true

editor: source

