{
  "hash": "be6888f4916a7125d1ea610caee0915d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"GEE and categorical responses\"\ndescription: \"Try using GEE for categorical responses\"\nauthor: \"Zhenglei Gao\"\ndate: \"01/14/2025\"\ncategories:\n  - code\n  - analysis\neditor_options: \n  chunk_output_type: console\n---\n\n## Use the data from previous posts\n\n\n## Multinomial or ordinal GEE\n\nData: Rheumatoid self-assessment scores for 302 patients, measured on a five-level ordinal response scale at three follow-up times.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(multgee)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: gnm\n```\n\n\n:::\n\n```{.r .cell-code}\ndata(arthritis)\nintrinsic.pars(y, arthritis, id, time) ## assess the underlying association pattern.\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6517843 0.9097341 0.9022272\n```\n\n\n:::\n\n```{.r .cell-code}\nfitmod <- ordLORgee(formula = y ~ factor(time) + factor(trt) + factor(baseline),\n  data = arthritis, id = id, repeated = time, LORstr = \"uniform\")\nsummary(fitmod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGEE FOR ORDINAL MULTINOMIAL RESPONSES \nversion 1.6.0 modified 2017-07-10 \n\nLink : Cumulative logit \n\nLocal Odds Ratios:\nStructure:         uniform\nModel:             3way\n\ncall:\nordLORgee(formula = y ~ factor(time) + factor(trt) + factor(baseline), \n    data = arthritis, id = id, repeated = time, LORstr = \"uniform\")\n\nSummary of residuals:\n      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. \n-0.5161111 -0.2399227 -0.0749670  0.0000219 -0.0066995  0.9932912 \n\nNumber of Iterations: 5 \n\nCoefficients:\n                  Estimate   san.se   san.z Pr(>|san.z|)    \nbeta10            -1.84315  0.38929 -4.7346      < 2e-16 ***\nbeta20             0.26692  0.35013  0.7624      0.44585    \nbeta30             2.23132  0.36625  6.0924      < 2e-16 ***\nbeta40             4.52542  0.42123 10.7434      < 2e-16 ***\nfactor(time)3      0.00140  0.12183  0.0115      0.99080    \nfactor(time)5     -0.36172  0.11395 -3.1743      0.00150 ** \nfactor(trt)2      -0.51212  0.16799 -3.0486      0.00230 ** \nfactor(baseline)2 -0.66963  0.38036 -1.7605      0.07832 .  \nfactor(baseline)3 -1.26070  0.35252 -3.5763      0.00035 ***\nfactor(baseline)4 -2.64373  0.41282 -6.4041      < 2e-16 ***\nfactor(baseline)5 -3.96613  0.53164 -7.4602      < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nLocal Odds Ratios Estimates:\n       [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9] [,10] [,11] [,12]\n [1,] 0.000 0.000 0.000 0.000 2.257 2.257 2.257 2.257 2.257 2.257 2.257 2.257\n [2,] 0.000 0.000 0.000 0.000 2.257 2.257 2.257 2.257 2.257 2.257 2.257 2.257\n [3,] 0.000 0.000 0.000 0.000 2.257 2.257 2.257 2.257 2.257 2.257 2.257 2.257\n [4,] 0.000 0.000 0.000 0.000 2.257 2.257 2.257 2.257 2.257 2.257 2.257 2.257\n [5,] 2.257 2.257 2.257 2.257 0.000 0.000 0.000 0.000 2.257 2.257 2.257 2.257\n [6,] 2.257 2.257 2.257 2.257 0.000 0.000 0.000 0.000 2.257 2.257 2.257 2.257\n [7,] 2.257 2.257 2.257 2.257 0.000 0.000 0.000 0.000 2.257 2.257 2.257 2.257\n [8,] 2.257 2.257 2.257 2.257 0.000 0.000 0.000 0.000 2.257 2.257 2.257 2.257\n [9,] 2.257 2.257 2.257 2.257 2.257 2.257 2.257 2.257 0.000 0.000 0.000 0.000\n[10,] 2.257 2.257 2.257 2.257 2.257 2.257 2.257 2.257 0.000 0.000 0.000 0.000\n[11,] 2.257 2.257 2.257 2.257 2.257 2.257 2.257 2.257 0.000 0.000 0.000 0.000\n[12,] 2.257 2.257 2.257 2.257 2.257 2.257 2.257 2.257 0.000 0.000 0.000 0.000\n\np-value of Null model: < 0.0001 \n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(fitmod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       2.5 %      97.5 %\nbeta10            -2.6061497 -1.08015721\nbeta20            -0.4193163  0.95314883\nbeta30             1.5134867  2.94915281\nbeta40             3.6998267  5.35101277\nfactor(time)3     -0.2373805  0.24018865\nfactor(time)5     -0.5850535 -0.13837735\nfactor(trt)2      -0.8413778 -0.18287050\nfactor(baseline)2 -1.4151270  0.07587068\nfactor(baseline)3 -1.9516257 -0.56978096\nfactor(baseline)4 -3.4528305 -1.83462340\nfactor(baseline)5 -5.0081187 -2.92413445\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggstats)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggstats' was built under R version 4.5.2\n```\n\n\n:::\n\n```{.r .cell-code}\nggcoef_multinom(fitmod)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `ggcoef_multicomponents()` was deprecated in ggstats 0.9.0.\nℹ Please use `ggcoef_dodged()` instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nℹ multgee model detected.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n✔ `tidy_multgee()` used instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nℹ Add `tidy_fun = broom.helpers::tidy_multgee` to quiet these messages.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](GEE_QB_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nWhat is the difference between Ordinal GEE and ordinal logistic regression? \n\n\n::: {.cell}\n\n:::\n\n\n## GEE Basics\n\n- It is a quasilikelihood approach.\n- Could include cluster/group correlation structure(e.g., repeated measurements from one subject)\n- No distributional assumption.\n- Could handle binary or categorical responses (multinomial).\n- Computationally simpler for categorical compared to maximum likelihood approach.\n- No likelihood based post hoc testing, comparison or inference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nURL <- \"http://static.lib.virginia.edu/statlab/materials/data/depression.csv\"\ndat <- read.csv(URL, stringsAsFactors = TRUE)\ndat$id <- factor(dat$id)\ndat$drug <- relevel(dat$drug, ref = \"standard\")\nhead(dat, n = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  diagnose     drug id time depression\n1     mild standard  1    0          1\n2     mild standard  1    1          1\n3     mild standard  1    2          1\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyverse' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'lubridate' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.6\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.2.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nwith(dat, tapply(depression, list(diagnose, drug, time), mean)) %>% \n  ftable() %>% \n  round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    0    1    2\n                               \nmild   standard  0.51 0.59 0.68\n       new       0.53 0.79 0.97\nsevere standard  0.21 0.28 0.46\n       new       0.18 0.50 0.83\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##install.packages(\"gee\")\nlibrary(gee) # version 4.13-25\ndep_gee <- gee(depression ~ diagnose + drug*time,\n               data = dat, \n               id = id, \n               family = binomial,\n               corstr = \"independence\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBeginning Cgee S-function, @(#) geeformula.q 4.13 98/01/27\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrunning glm to get initial regression estimate\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   (Intercept) diagnosesevere        drugnew           time   drugnew:time \n   -0.02798843    -1.31391092    -0.05960381     0.48241209     1.01744498 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(dep_gee)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n GEE:  GENERALIZED LINEAR MODELS FOR DEPENDENT DATA\n gee S-function, version 4.13 modified 98/01/27 (1998) \n\nModel:\n Link:                      Logit \n Variance to Mean Relation: Binomial \n Correlation Structure:     Independent \n\nCall:\ngee(formula = depression ~ diagnose + drug * time, id = id, data = dat, \n    family = binomial, corstr = \"independence\")\n\nSummary of Residuals:\n        Min          1Q      Median          3Q         Max \n-0.94844242 -0.40683252  0.05155758  0.38830952  0.80242231 \n\n\nCoefficients:\n                  Estimate Naive S.E.    Naive z Robust S.E.   Robust z\n(Intercept)    -0.02798843  0.1627083 -0.1720160   0.1741865 -0.1606808\ndiagnosesevere -1.31391092  0.1453432 -9.0400569   0.1459845 -9.0003423\ndrugnew        -0.05960381  0.2205812 -0.2702126   0.2285385 -0.2608042\ntime            0.48241209  0.1139224  4.2345663   0.1199350  4.0222784\ndrugnew:time    1.01744498  0.1874132  5.4288855   0.1876938  5.4207709\n\nEstimated Scale Parameter:  0.9854113\nNumber of Iterations:  1\n\nWorking Correlation\n     [,1] [,2] [,3]\n[1,]    1    0    0\n[2,]    0    1    0\n[3,]    0    0    1\n```\n\n\n:::\n\n```{.r .cell-code}\nres <- glm(depression ~ diagnose + drug*time,\n               data = dat,\n               family = quasibinomial)\nsummary(res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = depression ~ diagnose + drug * time, family = quasibinomial, \n    data = dat)\n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    -0.02799    0.16271  -0.172    0.863    \ndiagnosesevere -1.31391    0.14534  -9.040  < 2e-16 ***\ndrugnew        -0.05960    0.22058  -0.270    0.787    \ntime            0.48241    0.11392   4.235 2.50e-05 ***\ndrugnew:time    1.01744    0.18741   5.429 7.09e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for quasibinomial family taken to be 0.9854187)\n\n    Null deviance: 1411.9  on 1019  degrees of freedom\nResidual deviance: 1161.9  on 1015  degrees of freedom\nAIC: NA\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nThe “Estimated Scale Parameter” is reported as 0.9854113 = the dispersion parameter = similar to what is reported (Dispersion parameter for quasibinomial family taken to be 0.9854187) when running glm() with family = quasibinomial in order to model over-dispersion.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndep_gee2 <- gee(depression ~ diagnose + drug*time,\n               data = dat, \n               id = id, \n               family = binomial,\n               corstr = \"exchangeable\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBeginning Cgee S-function, @(#) geeformula.q 4.13 98/01/27\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrunning glm to get initial regression estimate\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   (Intercept) diagnosesevere        drugnew           time   drugnew:time \n   -0.02798843    -1.31391092    -0.05960381     0.48241209     1.01744498 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(dep_gee2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n GEE:  GENERALIZED LINEAR MODELS FOR DEPENDENT DATA\n gee S-function, version 4.13 modified 98/01/27 (1998) \n\nModel:\n Link:                      Logit \n Variance to Mean Relation: Binomial \n Correlation Structure:     Exchangeable \n\nCall:\ngee(formula = depression ~ diagnose + drug * time, id = id, data = dat, \n    family = binomial, corstr = \"exchangeable\")\n\nSummary of Residuals:\n        Min          1Q      Median          3Q         Max \n-0.94843397 -0.40683122  0.05156603  0.38832332  0.80238627 \n\n\nCoefficients:\n                  Estimate Naive S.E.    Naive z Robust S.E.   Robust z\n(Intercept)    -0.02809866  0.1625499 -0.1728617   0.1741791 -0.1613205\ndiagnosesevere -1.31391033  0.1448627 -9.0700418   0.1459630 -9.0016667\ndrugnew        -0.05926689  0.2205340 -0.2687427   0.2285569 -0.2593091\ntime            0.48246420  0.1141154  4.2278625   0.1199383  4.0226037\ndrugnew:time    1.01719312  0.1877051  5.4191018   0.1877014  5.4192084\n\nEstimated Scale Parameter:  0.985392\nNumber of Iterations:  2\n\nWorking Correlation\n             [,1]         [,2]         [,3]\n[1,]  1.000000000 -0.003432732 -0.003432732\n[2,] -0.003432732  1.000000000 -0.003432732\n[3,] -0.003432732 -0.003432732  1.000000000\n```\n\n\n:::\n\n```{.r .cell-code}\ndep_gee3 <- gee(depression ~ diagnose + drug*time,\n               data = dat, \n               id = id, \n               family = binomial,\n               corstr = \"AR-M\", Mv = 1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nBeginning Cgee S-function, @(#) geeformula.q 4.13 98/01/27\nrunning glm to get initial regression estimate\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   (Intercept) diagnosesevere        drugnew           time   drugnew:time \n   -0.02798843    -1.31391092    -0.05960381     0.48241209     1.01744498 \n```\n\n\n:::\n\n```{.r .cell-code}\ndep_gee3$working.correlation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             [,1]        [,2]         [,3]\n[1,] 1.000000e+00 0.008477443 7.186704e-05\n[2,] 8.477443e-03 1.000000000 8.477443e-03\n[3,] 7.186704e-05 0.008477443 1.000000e+00\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lme4) # version 1.1-31\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: Matrix\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'Matrix'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:tidyr':\n\n    expand, pack, unpack\n```\n\n\n:::\n\n```{.r .cell-code}\ndep_glmer <- glmer(depression ~ diagnose + drug*time + (1|id), \n               data = dat, family = binomial)\nsummary(dep_glmer, corr = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralized linear mixed model fit by maximum likelihood (Laplace\n  Approximation) [glmerMod]\n Family: binomial  ( logit )\nFormula: depression ~ diagnose + drug * time + (1 | id)\n   Data: dat\n\n     AIC      BIC   logLik deviance df.resid \n  1173.9   1203.5   -581.0   1161.9     1014 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-4.2849 -0.8268  0.2326  0.7964  2.0181 \n\nRandom effects:\n Groups Name        Variance Std.Dev.\n id     (Intercept) 0.003229 0.05682 \nNumber of obs: 1020, groups:  id, 340\n\nFixed effects:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)    -0.02796    0.16407  -0.170    0.865    \ndiagnosesevere -1.31488    0.15261  -8.616  < 2e-16 ***\ndrugnew        -0.05968    0.22240  -0.268    0.788    \ntime            0.48273    0.11566   4.174 3.00e-05 ***\ndrugnew:time    1.01817    0.19150   5.317 1.06e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggeffects) # version 1.2.0\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggeffects' was built under R version 4.5.2\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(ggemmeans(dep_glmer, terms = c(\"time\", \"drug\"), \n               condition = c(diagnose = \"severe\"))) + \n  ggplot2::ggtitle(\"GLMER Effect plot\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nYou are calculating adjusted predictions on the population-level (i.e.\n  `type = \"fixed\"`) for a *generalized* linear mixed model.\n  This may produce biased estimates due to Jensen's inequality. Consider\n  setting `bias_correction = TRUE` to correct for this bias.\n  See also the documentation of the `bias_correction` argument.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](GEE_QB_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans) # version 1.8.4-1\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'emmeans' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWelcome to emmeans.\nCaution: You lose important information if you filter this package's results.\nSee '? untidy'\n```\n\n\n:::\n\n```{.r .cell-code}\nemm_out <- emmeans(dep_gee2, specs = c(\"time\", \"drug\"), \n        at = list(diagnose = \"severe\"), \n        cov.keep = \"time\", \n        regrid = \"response\") %>% \n  as.data.frame()\nlibrary(ggplot2) # version 3.4.1\nggplot(emm_out) +\n  aes(x = time, y = prob, color = drug, fill = drug) +\n  geom_line() +\n  geom_ribbon(aes(ymin = asymp.LCL, ymax = asymp.UCL, \n                  color = NULL), alpha = 0.15) +\n  scale_color_brewer(palette = \"Set1\") +\n  scale_fill_brewer(palette = \"Set1\", guide = NULL) +\n  scale_y_continuous(labels = scales::percent) +\n  theme_ggeffects() +\n  labs(title = \"GEE Effect plot\", y = \"depression\")\n```\n\n::: {.cell-output-display}\n![](GEE_QB_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(geepack) # version 1.3.9\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'geepack' was built under R version 4.5.2\n```\n\n\n:::\n\n```{.r .cell-code}\ndep_gee4 <- geeglm(depression ~ diagnose + drug*time,\n                   data = dat,\n                   id = id,\n                   family = binomial,\n                   corstr = \"exchangeable\")\n# create effect plot\nplot(ggemmeans(dep_gee4, terms = c(\"time\", \"drug\"),\n               condition = c(diagnose = \"severe\"))) + \n  ggplot2::ggtitle(\"GEE Effect plot\")\n```\n\n::: {.cell-output-display}\n![](GEE_QB_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n## References\n\n- [Getting started with GEE](https://library.virginia.edu/data/articles/getting-started-with-generalized-estimating-equations)\n- [geepack R package]()\n- [A note on Weights in statistics](https://notstatschat.rbind.io/2020/08/04/weights-in-statistics/)\n\n## Additional references on survey data\n\n- [survey analysis](https://ladal.edu.au/surveys.html)\n\n",
    "supporting": [
      "GEE_QB_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}