---
title: "Set up docker locally"
description: "Reproduce "
author: "Zhenglei Gao"
date: "12/03/2024"
categories:
  - dev
  - docker
  - R
editor_options: 
  chunk_output_type: console
---


## References

- [The Ultimate Guide to Deploying a Shiny App on AWS](https://www.charlesbordet.com/en/guide-shiny-aws/#)
- [Amazon EC2 Instance Types](https://aws.amazon.com/ec2/instance-types/)

## When I have a Linux Computer

1. Remotely log on to that computer.
2. Install R, RStudio, Shinyserver.
3. Put the app package there.
4. Configure the ports.

## Steps I take to host the app on AWS

### 1. Create a new server in AWS

Follow the guidance, we use EC2 service. First we do the configuration for EC2 instance as my server.
- AMI(Amazon Machine Image):  Ubuntu Server 18.04 LTS.
- Instance type: t2.micro (CPU with one 1, 1 GB of RAM, basic internet connection, you can use this type for free)
- Storage size: default is 8 GB, up to 30 GB is free.
- Create a key pair to protect the access to the server, which is kept on my local computer.
 
Access the server with SSH.

- I can access under windows via SSH client PuTTY, or from Ubuntu system. 

Note that pem.key is the file that was saved as the key pair.

```
ssh -i "tutorial.pem" ubuntu@ec2-52-59-238-223.eu-central-1.compute.amazonaws.com
```


### 2. Install R and R shiny on the server
1. Add the CRAN repo

```bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
```

2. Install R

```bash
sudo apt update
sudo apt install r-base r-base-dev
```
3. Install shiny package

```bash
sudo R
> install.packages("shiny")

```

4. Install shinyserver

Modify the version as needed. 

```{bash}
sudo apt-get install gdebi-core
wget https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-1.5.13.944-amd64.deb
sudo gdebi shiny-server-1.5.13.944-amd64.deb
```

### 3. Deploy the app on the server

Copied from the guide^1

> From EC2 dashborad, select your instance.
> In the bottom half of your screen, find the line Security groups and click on the link.
> In the new window, again the bottom half of the screen, click on Inbound, the 2nd tab. Notice that only the port 22 is open.
> Click on Edit, and the popup that opens, enter the following settings:


EC2 dashboard $\rightarrow$ go to column IPv4 Public IP.


```
3.121.42.9:3838
```

Open the port 3838 on the firewall

AWS uses port 22 by default for SSH access. All other ports are blcoked.

### 4. Optional steps

- get a domain name
- install nginx, generate TLS certificates, and secure you app with HTTPS. 
- protect the app with a password
